CREATE TABLE users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, token_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE signup_otps (email text PRIMARY KEY, password_hash text NOT NULL, workspace_name text NOT NULL, code_hash text NOT NULL, expires_at timestamptz NOT NULL, attempts integer NOT NULL DEFAULT 0, sent_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE workspaces (id uuid PRIMARY KEY, name text NOT NULL, owner_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE workspace_members (workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('owner','admin','member')), PRIMARY KEY(workspace_id,user_id));
CREATE TABLE devices (id uuid PRIMARY KEY, workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), device_name text NOT NULL, platform text, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','revoked')), created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz);
CREATE TABLE pairing_sessions (id uuid PRIMARY KEY, workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, created_by uuid REFERENCES users(id), token_hash text UNIQUE NOT NULL, short_code_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz, attempts integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE operations (sequence bigserial PRIMARY KEY, operation_id uuid UNIQUE NOT NULL, workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, device_id uuid REFERENCES devices(id), user_id uuid REFERENCES users(id), order_id uuid NOT NULL, kind text NOT NULL, path text NOT NULL, payload jsonb NOT NULL, lamport_clock bigint NOT NULL, created_at timestamptz NOT NULL);
CREATE INDEX operations_workspace_sequence ON operations(workspace_id, sequence);
