import crypto from 'node:crypto'; import Fastify from 'fastify'; import cookie from '@fastify/cookie'; import cors from '@fastify/cors'; import rateLimit from '@fastify/rate-limit'; import argon2 from 'argon2'; import { Pool } from 'pg'; import { z } from 'zod';
const app = Fastify({ logger: true }), pool = new Pool({ connectionString: process.env.DATABASE_URL });
await app.register(cookie); await app.register(cors, { origin: process.env.WEB_ORIGIN || 'http://localhost:5173', credentials: true }); await app.register(rateLimit, { max: 20, timeWindow: '1 minute' });
app.get('/health', async ()=>{
    return {status:'ok'};
});
const id=()=>crypto.randomUUID(), hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex'), token=()=>crypto.randomBytes(24).toString('base64url');
async function me(r:any){const t=r.cookies.session;if(!t)return null;return (await pool.query('SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()',[hash(t)])).rows[0]||null;}
async function spaces(userId:string){return (await pool.query('SELECT w.id,w.name,m.role FROM workspaces w JOIN workspace_members m ON m.workspace_id=w.id WHERE m.user_id=$1',[userId])).rows;}
async function membership(userId:string,w:string){return (await pool.query('SELECT role FROM workspace_members WHERE user_id=$1 AND workspace_id=$2',[userId,w])).rows[0];}
async function login(reply:any,userId:string){const raw=token(),production=process.env.NODE_ENV==='production';await pool.query("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '30 days')",[id(),userId,hash(raw)]);reply.setCookie('session',raw,{httpOnly:true,secure:production,sameSite:production?'none':'lax',path:'/',maxAge:2592000});}
function auth(fn:any){return async(r:any,reply:any)=>{const u=await me(r);if(!u)return reply.code(401).send({error:'Authentication required'});return fn(r,reply,u);};}
const permittedEmail=z.string().email().transform(value=>value.toLowerCase()).refine(value=>value.endsWith('@gmail.com')||value.endsWith('@iiti.ac.in'),{message:'Use a @gmail.com or @iiti.ac.in email address'});
const parsedOrder=z.object({customer:z.string().nullable(),items:z.array(z.object({description:z.string(),quantity:z.number().int().min(1),attributes:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()]))})),dueDate:z.string().nullable(),amount:z.number().nullable(),needsClarification:z.boolean()});
app.post('/auth/signup',async(r:any,reply)=>{const x=z.object({email:permittedEmail,password:z.string().min(4),workspaceName:z.string().min(2).max(100)}).parse(r.body),c=await pool.connect();try{await c.query('BEGIN');const userId=id(),workspaceId=id();await c.query('INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)',[userId,x.email,await argon2.hash(x.password)]);await c.query('INSERT INTO workspaces(id,name,owner_id) VALUES($1,$2,$3)',[workspaceId,x.workspaceName,userId]);await c.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[workspaceId,userId]);await c.query('COMMIT');await login(reply,userId);return{id:userId,email:x.email,workspaces:await spaces(userId)};}catch(e:any){await c.query('ROLLBACK');return reply.code(e.code==='23505'?409:400).send({error:e.code==='23505'?'Account already exists':'Could not create account'});}finally{c.release();}});
app.post('/auth/login',async(r:any,reply)=>{const x=z.object({email:permittedEmail,password:z.string().min(4)}).parse(r.body),u=(await pool.query('SELECT * FROM users WHERE email=$1',[x.email])).rows[0];if(!u||!await argon2.verify(u.password_hash,x.password))return reply.code(401).send({error:'Invalid email or password'});await login(reply,u.id);return {id:u.id,email:u.email,workspaces:await spaces(u.id)};});
app.post('/auth/logout',auth(async(r:any,reply:any)=>{await pool.query('DELETE FROM sessions WHERE token_hash=$1',[hash(r.cookies.session)]);reply.clearCookie('session',{path:'/'});return{ok:true};}));app.get('/auth/me',auth(async(_:any,_r:any,u:any)=>({...u,workspaces:await spaces(u.id)})));
app.post('/workspaces',auth(async(r:any,_reply:any,u:any)=>{const x=z.object({name:z.string().min(2).max(100)}).parse(r.body),w=id();await pool.query('INSERT INTO workspaces(id,name,owner_id) VALUES($1,$2,$3)',[w,x.name,u.id]);await pool.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[w,u.id]);return{id:w,name:x.name,role:'owner'};}));
app.get('/workspaces',auth(async(_:any,_reply:any,u:any)=>spaces(u.id)));
app.post('/workspaces/:id/members',auth(async(r:any,reply:any,u:any)=>{const x=z.object({email:z.string().email(),role:z.enum(['admin','member']).default('member')}).parse(r.body),w=String(r.params.id),mine=await membership(u.id,w),person=(await pool.query('SELECT id FROM users WHERE email=$1',[x.email.toLowerCase()])).rows[0];if(!mine||mine.role==='member')return reply.code(403).send({error:'Admin permission required'});if(!person)return reply.code(404).send({error:'Create the user account before adding them'});await pool.query('INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=EXCLUDED.role',[w,person.id,x.role]);return{ok:true};}));
app.post('/devices/register',auth(async(r:any,reply:any,u:any)=>{const x=z.object({workspaceId:z.string().uuid(),deviceId:z.string().uuid(),deviceName:z.string().min(1),platform:z.string().min(1)}).parse(r.body);if(!await membership(u.id,x.workspaceId))return reply.code(403).send({error:'Workspace denied'});await pool.query("INSERT INTO devices(id,workspace_id,user_id,device_name,platform) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET last_seen_at=now(),device_name=EXCLUDED.device_name,platform=EXCLUDED.platform",[x.deviceId,x.workspaceId,u.id,x.deviceName,x.platform]);return{ok:true};}));
app.get('/devices',auth(async(r:any,reply:any,u:any)=>{const w=String(r.headers['x-workspace-id']||'');if(!await membership(u.id,w))return reply.code(403).send({error:'Workspace denied'});return(await pool.query('SELECT id,device_name,platform,status,created_at,last_seen_at,revoked_at FROM devices WHERE workspace_id=$1',[w])).rows;}));
app.post('/devices/pair/start',auth(async(r:any,reply:any,u:any)=>{const w=String(r.headers['x-workspace-id']||''),device=String(r.headers['x-device-id']||'');if(!await membership(u.id,w)||(await pool.query("SELECT 1 FROM devices WHERE id=$1 AND status='active'",[device])).rows.length===0)return reply.code(403).send({error:'Active device required'});const session=id(),secret=token(),short=crypto.randomBytes(4).toString('hex').toUpperCase();await pool.query("INSERT INTO pairing_sessions(id,workspace_id,created_by,token_hash,short_code_hash,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '10 minutes')",[session,w,u.id,hash(secret),hash(short)]);return{qrPayload:`${session}.${secret}`,shortCode:short,expiresInSeconds:600};}));
app.post('/devices/pair/complete',auth(async(r:any,reply:any,u:any)=>{const x=z.object({code:z.string(),deviceId:z.string().uuid(),deviceName:z.string(),platform:z.string()}).parse(r.body),parts=x.code.split('.'),q=parts.length===2?'UPDATE pairing_sessions SET used_at=now(),attempts=attempts+1 WHERE id=$1 AND token_hash=$2 AND expires_at>now() AND used_at IS NULL RETURNING workspace_id':'UPDATE pairing_sessions SET used_at=now(),attempts=attempts+1 WHERE short_code_hash=$1 AND expires_at>now() AND used_at IS NULL RETURNING workspace_id',args=parts.length===2?[parts[0],hash(parts[1])]:[hash(x.code.toUpperCase())],p=(await pool.query(q,args)).rows[0];if(!p)return reply.code(400).send({error:'Invalid, expired, or already used pairing code'});if(!await membership(u.id,p.workspace_id))return reply.code(403).send({error:'You must be a workspace member before pairing'});await pool.query('INSERT INTO devices(id,workspace_id,user_id,device_name,platform) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING',[x.deviceId,p.workspace_id,u.id,x.deviceName,x.platform]);return{workspaceId:p.workspace_id};}));
app.patch('/devices/:id/revoke',auth(async(r:any,reply:any,u:any)=>{const d=(await pool.query('SELECT workspace_id FROM devices WHERE id=$1',[r.params.id])).rows[0],m=d&&await membership(u.id,d.workspace_id);if(!m||m.role==='member')return reply.code(403).send({error:'Admin permission required'});await pool.query("UPDATE devices SET status='revoked',revoked_at=now() WHERE id=$1",[r.params.id]);return{ok:true};}));
app.post('/api/parse-order',async(r:any,reply:any)=>{const x=z.object({message:z.string().min(1).max(4000)}).parse(r.body);if(!process.env.MODEL_SERVICE_URL)return reply.code(503).send({error:'Model parser is not configured'});try{const response=await fetch(`${process.env.MODEL_SERVICE_URL.replace(/\/$/,'')}/parse`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:x.message})});if(!response.ok)throw new Error(`Model service returned ${response.status}`);return parsedOrder.parse(await response.json());}catch(error){app.log.warn({error},'Model parser unavailable');return reply.code(503).send({error:'Model parser is unavailable'});}});
async function activeDevice(r:any,u:any,w:string){const d=String(r.headers['x-device-id']||'');return (await pool.query("SELECT 1 FROM devices WHERE id=$1 AND user_id=$2 AND workspace_id=$3 AND status='active'",[d,u.id,w])).rows.length?d:null;}
app.post('/sync/push',auth(async(r:any,reply:any,u:any)=>{const x=z.object({workspaceId:z.string().uuid(),operations:z.array(z.object({operationId:z.string().uuid(),workspaceId:z.string().uuid(),deviceId:z.string().uuid(),userId:z.string().uuid(),orderId:z.string().uuid(),kind:z.enum(['set','delete_order','delete_item']),path:z.string(),value:z.unknown(),lamportClock:z.number().int().positive(),createdAt:z.string().datetime()})).max(200)}).parse(r.body),d=await activeDevice(r,u,x.workspaceId);if(!d||!await membership(u.id,x.workspaceId))return reply.code(403).send({error:'Device denied'});for(const o of x.operations){if(o.workspaceId!==x.workspaceId||o.deviceId!==d||o.userId!==u.id)return reply.code(400).send({error:'Invalid operation'});await pool.query('INSERT INTO operations(operation_id,workspace_id,device_id,user_id,order_id,kind,path,payload,lamport_clock,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(operation_id) DO NOTHING',[o.operationId,o.workspaceId,o.deviceId,o.userId,o.orderId,o.kind,o.path,JSON.stringify(o.value),o.lamportClock,o.createdAt]);}return{acknowledged:x.operations.map(o=>o.operationId)};}));
app.post('/sync/pull',auth(async(r:any,reply:any,u:any)=>{const x=z.object({workspaceId:z.string().uuid(),cursor:z.coerce.number().int().min(0)}).parse(r.body);if(!await activeDevice(r,u,x.workspaceId))return reply.code(403).send({error:'Device denied'});const rows=(await pool.query('SELECT * FROM operations WHERE workspace_id=$1 AND sequence>$2 ORDER BY sequence LIMIT 500',[x.workspaceId,x.cursor])).rows;return{cursor:Number(rows.at(-1)?.sequence||x.cursor),operations:rows.map(o=>({operationId:o.operation_id,workspaceId:o.workspace_id,deviceId:o.device_id,userId:o.user_id,orderId:o.order_id,kind:o.kind,path:o.path,value:o.payload,lamportClock:Number(o.lamport_clock),createdAt:o.created_at}))};}));
app.listen({port:Number(process.env.PORT||3001),host:'0.0.0.0'});
