import { useEffect, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { QRCodeSVG } from 'qrcode.react';
import { db } from './db/db'; import { createOrder, getDevice, mutate } from './services/orderService'; import { enableAutoSync, syncWorkspace } from './services/syncService'; import { parseOrder } from './services/parser'; import type { Order, SyncState } from './types/domain';
const API = import.meta.env.VITE_API_URL || 'http://localhost:3001';
type Workspace={id:string;name:string;role:'owner'|'admin'|'member'}; type User={id:string;email:string;workspaces:Workspace[]}; type Device={id:string;device_name:string;platform:string;status:'active'|'revoked';last_seen_at:string};
async function request(path:string, options:RequestInit={}) { const r=await fetch(`${API}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const body=await r.json().catch(()=>({})); if(!r.ok)throw new Error(body.error||'Request failed');return body; }
export default function App(){
 const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState<'login'|'signup'|'otp'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[business,setBusiness]=useState(''),[otp,setOtp]=useState(''),[notice,setNotice]=useState(''),[devOtp,setDevOtp]=useState(''),[workspaceId,setWorkspaceId]=useState(''),[message,setMessage]=useState(''),[devices,setDevices]=useState<Device[]>([]),[pair,setPair]=useState<{qrPayload:string;shortCode:string}|null>(null),[joinCode,setJoinCode]=useState(''),[memberEmail,setMemberEmail]=useState('');
 const orders=useLiveQuery<Order[]>(()=>workspaceId?db.orders.where('workspaceId').equals(workspaceId).filter(x=>!x.deleted).reverse().sortBy('updatedAt'):Promise.resolve<Order[]>([]),[workspaceId])??[]; const sync=useLiveQuery<SyncState|undefined>(()=>workspaceId?db.syncState.get(workspaceId):Promise.resolve(undefined),[workspaceId]); const pending=useLiveQuery(()=>db.outbox.where('status').anyOf('pending','error').count(),[])||0;
 const save=(u:User)=>{setUser(u);localStorage.setItem('order-desk-user',JSON.stringify(u));if(!workspaceId)setWorkspaceId(u.workspaces[0]?.id||'');};
 useEffect(()=>{request('/auth/me').then(save).catch(()=>{const saved=localStorage.getItem('order-desk-user');if(saved)save(JSON.parse(saved));});},[]);
 useEffect(()=>workspaceId?enableAutoSync(workspaceId):undefined,[workspaceId]);
 useEffect(()=>{if(!user||!workspaceId)return;void registerAndLoad();},[user?.id,workspaceId]);
 async function registerAndLoad(){try{const d=await getDevice();await request('/devices/register',{method:'POST',body:JSON.stringify({workspaceId,deviceId:d.deviceId,deviceName:d.deviceName,platform:d.platform})});setDevices(await request('/devices',{headers:{'X-Workspace-Id':workspaceId}}));void syncWorkspace(workspaceId);}catch(e){setNotice(e instanceof Error?e.message:'Working offline — changes stay on this device.');}}
 async function login(){try{save(await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})}));setNotice('Signed in.');}catch(e){setNotice(e instanceof Error?e.message:'Login failed');}}
 async function requestOtp(){try{const r=await request('/auth/signup/request-otp',{method:'POST',body:JSON.stringify({email,password,workspaceName:business})});setDevOtp(r.devOtp||'');setMode('otp');setNotice('Verification code sent.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to send code');}}
 async function verifyOtp(){try{save(await request('/auth/signup/verify-otp',{method:'POST',body:JSON.stringify({email,otp})}));setNotice('Account verified. Your first device is being registered.');}catch(e){setNotice(e instanceof Error?e.message:'Verification failed');}}
 async function logout(){await request('/auth/logout',{method:'POST'}).catch(()=>undefined);localStorage.removeItem('order-desk-user');setUser(null);setWorkspaceId('');setDevices([]);}
 async function addOrder(){if(!message.trim()||!user)return;const p=await parseOrder(message);await createOrder(workspaceId,user.id,{customer:p.customer||undefined,description:p.items[0]?.description,quantity:p.items[0]?.quantity,amount:p.amount||undefined,dueDate:p.dueDate||undefined});setMessage('');void syncWorkspace(workspaceId);}
 async function createPair(){try{const d=await getDevice();setPair(await request('/devices/pair/start',{method:'POST',headers:{'X-Workspace-Id':workspaceId,'X-Device-Id':d.deviceId},body:'{}'}));}catch(e){setNotice(e instanceof Error?e.message:'Pairing failed');}}
 async function joinDevice(){try{const d=await getDevice(), result=await request('/devices/pair/complete',{method:'POST',body:JSON.stringify({code:joinCode.trim(),deviceId:d.deviceId,deviceName:d.deviceName,platform:d.platform})});setWorkspaceId(result.workspaceId);setJoinCode('');setNotice('This device joined the workspace.');}catch(e){setNotice(e instanceof Error?e.message:'Could not join');}}
 async function revoke(deviceId:string){try{await request(`/devices/${deviceId}/revoke`,{method:'PATCH'});await registerAndLoad();}catch(e){setNotice(e instanceof Error?e.message:'Could not revoke device');}}
 async function addMember(){try{await request(`/workspaces/${workspaceId}/members`,{method:'POST',body:JSON.stringify({email:memberEmail,role:'member'})});setMemberEmail('');setNotice('Workspace member added. They can now sign in and pair their own device.');}catch(e){setNotice(e instanceof Error?e.message:'Could not add member');}}
 if(!user)return <main className="auth"><h1>Order Desk</h1><p>Offline-first order management</p>{mode==='otp'?<><p>Enter the six-digit code sent to <b>{email}</b>.</p><input inputMode="numeric" maxLength={6} placeholder="123456" value={otp} onChange={e=>setOtp(e.target.value)}/>{devOtp&&<small className="dev">Development OTP: {devOtp}</small>}<button onClick={verifyOtp}>Verify & create account</button><button className="link" onClick={()=>setMode('signup')}>Back</button></>:<><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password (10+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/>{mode==='signup'&&<input placeholder="Business name" value={business} onChange={e=>setBusiness(e.target.value)}/>}<button onClick={mode==='login'?login:requestOtp}>{mode==='login'?'Log in':'Send verification code'}</button><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create an account':'I already have an account'}</button></>}<small className="notice">{notice}</small></main>;
 return <main className="app"><header><div><h1>Order Desk</h1><small>{navigator.onLine?'ONLINE':'OFFLINE'} · {sync?.status?.toUpperCase()||'LOCAL'} · {pending} pending</small></div><div className="headerActions"><button onClick={()=>void syncWorkspace(workspaceId)}>Sync now</button><button className="quiet" onClick={logout}>Log out</button></div></header><section className="toolbar"><select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}>{user.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><button onClick={createPair}>Add device</button></section>{notice&&<p className="notice">{notice}</p>}<section className="pair"><h2>Devices</h2><div className="join"><input placeholder="Paste QR text or enter short code" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/><button onClick={joinDevice}>Join workspace</button></div>{user.workspaces.find(w=>w.id===workspaceId)?.role!=='member'&&<div className="join"><input type="email" placeholder="Existing user email to add" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)}/><button onClick={addMember}>Add staff</button></div>}{pair&&<div className="pairCard"><QRCodeSVG value={pair.qrPayload} size={140}/><p>Scan this QR on the new device or use:</p><code>{pair.shortCode}</code><small>Expires in 10 minutes. One use only.</small></div>}<div className="deviceList">{devices.map(d=><div key={d.id}><span><b>{d.device_name}</b> · {d.platform} · {d.status}</span>{(user.workspaces.find(w=>w.id===workspaceId)?.role!=='member'&&d.status==='active')&&<button className="danger" onClick={()=>revoke(d.id)}>Revoke</button>}</div>)}</div></section><section className="composer"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Paste a customer message or describe a new order…"/><button onClick={addOrder}>Parse & save offline</button></section><section className="orders"><h2>Orders</h2>{orders.map(o=><article key={o.id}><div><strong>{o.customer||'Walk-in customer'}</strong><span>{o.status}</span></div><p>{o.items.map(i=>`${i.quantity} × ${i.description}`).join(', ')}</p><small>Due {o.dueDate||'not set'} · ₹{o.amount??'—'}</small><button onClick={()=>user&&void mutate(workspaceId,user.id,o.id,'isPaid',!o.isPaid)}>Mark {o.isPaid?'unpaid':'paid'}</button><button className="danger" onClick={()=>user&&void mutate(workspaceId,user.id,o.id,'__deleted',true,'delete_order')}>Delete</button></article>)}{!orders.length&&<p className="empty">No local orders yet. You can create one without a network connection.</p>}</section><footer>{sync?.lastError&&`Sync error: ${sync.lastError}`}</footer></main>;
}
